export const productList = [
  {
    no: 7,
    productName: "Alamos Malbec Argentina",
    productType: "Red Wine",
    productPrice: "Rp395.000",
    productImage: require("../assets/ProductImage/Red Wine/Alamos Malbec Argentina.png"),
  },
  {
    no: 8,
    productName: "Antigal Estimulo Cabernet Sauvignon",
    productType: "Red Wine",
    productPrice: "Rp320.000",
    productImage: require("../assets/ProductImage/Red Wine/Antigal Estimulo Cabernet Sauvignon.png"),
  },
  {
    no: 9,
    productName:
      "Chateau De La Negly la Falaise Rouge 2018 Red Wine France 15.5% alc",
    productType: "Red Wine",
    productPrice: "Rp785.000",
    productImage: require("../assets/ProductImage/Red Wine/Chateau De La Negly la Falaise Rouge 2018 Red Wine France 15.5 alc.png"),
  },
  {
    no: 10,
    productName:
      "Chateau Saint Romans 2018 Bordeaux France Red Wine 14% alc 750ml",
    productType: "Red Wine",
    productPrice: "Rp350.000",
    productImage: require("../assets/ProductImage/Red Wine/Chateau Saint Romans 2018 Bordeaux France Red Wine 14 alc 750ml.png"),
  },
  {
    no: 11,
    productName: "Clarendelle Rouge 2015 Bordeaux Red Wine France",
    productType: "Red Wine",
    productPrice: "Rp635.000",
    productImage: require("../assets/ProductImage/Red Wine/Clarendelle Rouge 2015 Bordeaux Red Wine France.jfif"),
  },
  {
    no: 12,
    productName: "D'Alamel Reserva Cabernet Merlot 2018 Chile",
    productType: "Red Wine",
    productPrice: "Rp400.000",
    productImage: require("../assets/ProductImage/Red Wine/D'Alamel Reserva Cabernet Merlot 2018 Chille.png"),
  },
  {
    no: 13,
    productName: "D'Alamel Reserva Cabernet Sauvignon 2018 Chile",
    productType: "Red Wine",
    productPrice: "Rp400.000",
    productImage: require("../assets/ProductImage/Red Wine/D'Alamel Reserva Cabernet Sauvignon 2018 Chille.png"),
  },
  {
    no: 14,
    productName: "Decoy Cabernet Sauvignon 2019 California United States",
    productType: "Red Wine",
    productPrice: "Rp720.000",
    productImage: require("../assets/ProductImage/Red Wine/Decoy Cabernet Sauvignon 2019 California United States.jpg"),
  },
  {
    no: 15,
    productName: "Alamos Malbec Argentina",
    productType: "Soju",
    productPrice: "Rp395.000",
    productImage: require("../assets/ProductImage/Soju/Chum Churum Apple Manggo.png"),
  },
  {
    no: 16,
    productName: "Chum Churum Apple",
    productType: "Soju",
    productPrice: "Rp100.000",
    productImage: require("../assets/ProductImage/Soju/Chum Churum Apple.png"),
  },
  {
    no: 17,
    productName: "Chum Churum Blueberry",
    productType: "Soju",
    productPrice: "Rp100.000",
    productImage: require("../assets/ProductImage/Soju/Chum Churum Blueberry.png"),
  },
  {
    no: 18,
    productName: "Chum Churum Original",
    productType: "Soju",
    productPrice: "Rp100.000",
    productImage: require("../assets/ProductImage/Soju/Chum Churum Original.jfif"),
  },
  {
    no: 19,
    productName: "Chum Churum Peach",
    productType: "Soju",
    productPrice: "Rp100.000",
    productImage: require("../assets/ProductImage/Soju/Chum Churum Peach.png"),
  },
  {
    no: 20,
    productName: "Chum Churum Yoghurt",
    productType: "Soju",
    productPrice: "Rp100.000",
    productImage: require("../assets/ProductImage/Soju/Chum Churum Yoghurt.jpg"),
  },
  {
    no: 21,
    productName: "Jinro Chamisul Fresh - Original",
    productType: "Soju",
    productPrice: "Rp105.000",
    productImage: require("../assets/ProductImage/Soju/Jinro Chamisul Fresh - Original.jpg"),
  },
  {
    no: 22,
    productName: "Jinro Chamisul Grape Fruit",
    productType: "Soju",
    productPrice: "Rp105.000",
    productImage: require("../assets/ProductImage/Soju/Jinro Chamisul Grape Fruit.webp"),
  },
];
